<?php
/**
 * DefaultApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DefaultApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApi
{

    /**
     * API Client
     * @var \Swagger\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Swagger\Client\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('http://172.16.6.201/WSEditFOBA');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \Swagger\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \Swagger\Client\ApiClient $apiClient set the API client
     * @return DefaultApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * obtenirEditionRetraite
     *
     * 
     *
     * @param \Swagger\Client\Model\SimulationRetraite $simulation_retraite contient les donn\u00E9es n\u00E9cessaires \u00E0 l&#39;\u00E9dition de la simulation retraite experte effectu\u00E9e depuis SimRETAI (required)
     * @return ByteArray[]
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function obtenirEditionRetraite($simulation_retraite)
    {
        list($response, $statusCode, $httpHeader) = $this->obtenirEditionRetraiteWithHttpInfo ($simulation_retraite);
        return $response; 
    }


    /**
     * obtenirEditionRetraiteWithHttpInfo
     *
     * 
     *
     * @param \Swagger\Client\Model\SimulationRetraite $simulation_retraite contient les donn\u00E9es n\u00E9cessaires \u00E0 l&#39;\u00E9dition de la simulation retraite experte effectu\u00E9e depuis SimRETAI (required)
     * @return Array of ByteArray[], HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function obtenirEditionRetraiteWithHttpInfo($simulation_retraite)
    {
        
        // verify the required parameter 'simulation_retraite' is set
        if ($simulation_retraite === null) {
            throw new \InvalidArgumentException('Missing the required parameter $simulation_retraite when calling obtenirEditionRetraite');
        }
  
        // parse inputs
        $resourcePath = "/retraite";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/pdf'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($simulation_retraite)) {
            $_tempBody = $simulation_retraite;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, 'ByteArray[]'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Swagger\Client\ObjectSerializer::deserialize($response, 'ByteArray[]', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), 'ByteArray[]', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            default:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), '\Swagger\Client\Model\ErrorModel', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * obtenirEditionSimulations360
     *
     * 
     *
     * @param \Swagger\Client\Model\DossierSimulations $dossier_simulations contient les donn\u00E9es n\u00E9cessaires \u00E0 l&#39;\u00E9dition des diff\u00E9rentes simulations chain\u00E9es (required)
     * @return ByteArray[]
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function obtenirEditionSimulations360($dossier_simulations)
    {
        list($response, $statusCode, $httpHeader) = $this->obtenirEditionSimulations360WithHttpInfo ($dossier_simulations);
        return $response; 
    }


    /**
     * obtenirEditionSimulations360WithHttpInfo
     *
     * 
     *
     * @param \Swagger\Client\Model\DossierSimulations $dossier_simulations contient les donn\u00E9es n\u00E9cessaires \u00E0 l&#39;\u00E9dition des diff\u00E9rentes simulations chain\u00E9es (required)
     * @return Array of ByteArray[], HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function obtenirEditionSimulations360WithHttpInfo($dossier_simulations)
    {
        
        // verify the required parameter 'dossier_simulations' is set
        if ($dossier_simulations === null) {
            throw new \InvalidArgumentException('Missing the required parameter $dossier_simulations when calling obtenirEditionSimulations360');
        }
  
        // parse inputs
        $resourcePath = "/simulations360";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/pdf'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($dossier_simulations)) {
            $_tempBody = $dossier_simulations;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, 'ByteArray[]'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Swagger\Client\ObjectSerializer::deserialize($response, 'ByteArray[]', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), 'ByteArray[]', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            default:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), '\Swagger\Client\Model\ErrorModel', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
}
