<?php
/**
 * Montant
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * Montant Class Doc Comment
 *
 * @category    Class
 * @description montant avec devise
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Montant implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'montant' => 'float',
        'monnaie' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'montant' => 'montant',
        'monnaie' => 'monnaie'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'montant' => 'setMontant',
        'monnaie' => 'setMonnaie'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'montant' => 'getMontant',
        'monnaie' => 'getMonnaie'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $montant montant pouvant \u00EAtre n\u00E9gatif ou positif
      * @var float
      */
    protected $montant;
    
    /**
      * $monnaie symbole de la devise
      * @var string
      */
    protected $monnaie;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->montant = $data["montant"];
            $this->monnaie = $data["monnaie"];
        }
    }
    
    /**
     * Gets montant
     * @return float
     */
    public function getMontant()
    {
        return $this->montant;
    }
  
    /**
     * Sets montant
     * @param float $montant montant pouvant \u00EAtre n\u00E9gatif ou positif
     * @return $this
     */
    public function setMontant($montant)
    {
        
        $this->montant = $montant;
        return $this;
    }
    
    /**
     * Gets monnaie
     * @return string
     */
    public function getMonnaie()
    {
        return $this->monnaie;
    }
  
    /**
     * Sets monnaie
     * @param string $monnaie symbole de la devise
     * @return $this
     */
    public function setMonnaie($monnaie)
    {
        $allowed_values = array("€", "F");
        if (!in_array($monnaie, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'monnaie', must be one of '€', 'F'");
        }
        $this->monnaie = $monnaie;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
