<?php
/**
 * ParametrageRente
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * ParametrageRente Class Doc Comment
 *
 * @category    Class
 * @description param\u00E9trage s\u00E9lectionn\u00E9e pour la rente
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ParametrageRente implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'type_rente' => 'string',
        'taux_reversion_rente' => 'float',
        'date_naissance_benef_reversion' => '\DateTime',
        'nombre_annees_annuites_garanties' => 'int'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'type_rente' => 'typeRente',
        'taux_reversion_rente' => 'tauxReversionRente',
        'date_naissance_benef_reversion' => 'dateNaissanceBenefReversion',
        'nombre_annees_annuites_garanties' => 'nombreAnneesAnnuitesGaranties'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'type_rente' => 'setTypeRente',
        'taux_reversion_rente' => 'setTauxReversionRente',
        'date_naissance_benef_reversion' => 'setDateNaissanceBenefReversion',
        'nombre_annees_annuites_garanties' => 'setNombreAnneesAnnuitesGaranties'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'type_rente' => 'getTypeRente',
        'taux_reversion_rente' => 'getTauxReversionRente',
        'date_naissance_benef_reversion' => 'getDateNaissanceBenefReversion',
        'nombre_annees_annuites_garanties' => 'getNombreAnneesAnnuitesGaranties'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $type_rente vaut Rente viag\u00E8re - Rente avec annuit\u00E9 garantie
      * @var string
      */
    protected $type_rente;
    
    /**
      * $taux_reversion_rente taux de reversion exprim\u00E9 en centieme
      * @var float
      */
    protected $taux_reversion_rente;
    
    /**
      * $date_naissance_benef_reversion date de naissance du beneficiaire de la reversion
      * @var \DateTime
      */
    protected $date_naissance_benef_reversion;
    
    /**
      * $nombre_annees_annuites_garanties nombre ann\u00E9e annuit\u00E9 garantie
      * @var int
      */
    protected $nombre_annees_annuites_garanties;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->type_rente = $data["type_rente"];
            $this->taux_reversion_rente = $data["taux_reversion_rente"];
            $this->date_naissance_benef_reversion = $data["date_naissance_benef_reversion"];
            $this->nombre_annees_annuites_garanties = $data["nombre_annees_annuites_garanties"];
        }
    }
    
    /**
     * Gets type_rente
     * @return string
     */
    public function getTypeRente()
    {
        return $this->type_rente;
    }
  
    /**
     * Sets type_rente
     * @param string $type_rente vaut Rente viag\u00E8re - Rente avec annuit\u00E9 garantie
     * @return $this
     */
    public function setTypeRente($type_rente)
    {
        
        $this->type_rente = $type_rente;
        return $this;
    }
    
    /**
     * Gets taux_reversion_rente
     * @return float
     */
    public function getTauxReversionRente()
    {
        return $this->taux_reversion_rente;
    }
  
    /**
     * Sets taux_reversion_rente
     * @param float $taux_reversion_rente taux de reversion exprim\u00E9 en centieme
     * @return $this
     */
    public function setTauxReversionRente($taux_reversion_rente)
    {
        
        $this->taux_reversion_rente = $taux_reversion_rente;
        return $this;
    }
    
    /**
     * Gets date_naissance_benef_reversion
     * @return \DateTime
     */
    public function getDateNaissanceBenefReversion()
    {
        return $this->date_naissance_benef_reversion;
    }
  
    /**
     * Sets date_naissance_benef_reversion
     * @param \DateTime $date_naissance_benef_reversion date de naissance du beneficiaire de la reversion
     * @return $this
     */
    public function setDateNaissanceBenefReversion($date_naissance_benef_reversion)
    {
        
        $this->date_naissance_benef_reversion = $date_naissance_benef_reversion;
        return $this;
    }
    
    /**
     * Gets nombre_annees_annuites_garanties
     * @return int
     */
    public function getNombreAnneesAnnuitesGaranties()
    {
        return $this->nombre_annees_annuites_garanties;
    }
  
    /**
     * Sets nombre_annees_annuites_garanties
     * @param int $nombre_annees_annuites_garanties nombre ann\u00E9e annuit\u00E9 garantie
     * @return $this
     */
    public function setNombreAnneesAnnuitesGaranties($nombre_annees_annuites_garanties)
    {
        
        $this->nombre_annees_annuites_garanties = $nombre_annees_annuites_garanties;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
