<?php
/**
 * ServiceNational
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * ServiceNational Class Doc Comment
 *
 * @category    Class
 * @description description p\u00E9riode sp\u00E9cifique de Service National
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServiceNational implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'date_debut_service_national' => '\DateTime',
        'date_fin_service_national' => '\DateTime'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'date_debut_service_national' => 'dateDebutServiceNational',
        'date_fin_service_national' => 'dateFinServiceNational'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'date_debut_service_national' => 'setDateDebutServiceNational',
        'date_fin_service_national' => 'setDateFinServiceNational'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'date_debut_service_national' => 'getDateDebutServiceNational',
        'date_fin_service_national' => 'getDateFinServiceNational'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $date_debut_service_national date de d\u00E9but du service national
      * @var \DateTime
      */
    protected $date_debut_service_national;
    
    /**
      * $date_fin_service_national date de fin du service national
      * @var \DateTime
      */
    protected $date_fin_service_national;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->date_debut_service_national = $data["date_debut_service_national"];
            $this->date_fin_service_national = $data["date_fin_service_national"];
        }
    }
    
    /**
     * Gets date_debut_service_national
     * @return \DateTime
     */
    public function getDateDebutServiceNational()
    {
        return $this->date_debut_service_national;
    }
  
    /**
     * Sets date_debut_service_national
     * @param \DateTime $date_debut_service_national date de d\u00E9but du service national
     * @return $this
     */
    public function setDateDebutServiceNational($date_debut_service_national)
    {
        
        $this->date_debut_service_national = $date_debut_service_national;
        return $this;
    }
    
    /**
     * Gets date_fin_service_national
     * @return \DateTime
     */
    public function getDateFinServiceNational()
    {
        return $this->date_fin_service_national;
    }
  
    /**
     * Sets date_fin_service_national
     * @param \DateTime $date_fin_service_national date de fin du service national
     * @return $this
     */
    public function setDateFinServiceNational($date_fin_service_national)
    {
        
        $this->date_fin_service_national = $date_fin_service_national;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
