<?php
/**
 * SyntheseRIS
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * SyntheseRIS Class Doc Comment
 *
 * @category    Class
 * @description ensemble des informations pr\u00E9sentes sur le RIS
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SyntheseRIS implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'nb_trimestres_assurance_total' => 'int',
        'cumuls_regime' => '\Swagger\Client\Model\CumulRegime[]'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'nb_trimestres_assurance_total' => 'nbTrimestresAssuranceTotal',
        'cumuls_regime' => 'cumulsRegime'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'nb_trimestres_assurance_total' => 'setNbTrimestresAssuranceTotal',
        'cumuls_regime' => 'setCumulsRegime'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'nb_trimestres_assurance_total' => 'getNbTrimestresAssuranceTotal',
        'cumuls_regime' => 'getCumulsRegime'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $nb_trimestres_assurance_total nombre de trimestres d'assurance
      * @var int
      */
    protected $nb_trimestres_assurance_total;
    
    /**
      * $cumuls_regime 
      * @var \Swagger\Client\Model\CumulRegime[]
      */
    protected $cumuls_regime;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->nb_trimestres_assurance_total = $data["nb_trimestres_assurance_total"];
            $this->cumuls_regime = $data["cumuls_regime"];
        }
    }
    
    /**
     * Gets nb_trimestres_assurance_total
     * @return int
     */
    public function getNbTrimestresAssuranceTotal()
    {
        return $this->nb_trimestres_assurance_total;
    }
  
    /**
     * Sets nb_trimestres_assurance_total
     * @param int $nb_trimestres_assurance_total nombre de trimestres d'assurance
     * @return $this
     */
    public function setNbTrimestresAssuranceTotal($nb_trimestres_assurance_total)
    {
        
        $this->nb_trimestres_assurance_total = $nb_trimestres_assurance_total;
        return $this;
    }
    
    /**
     * Gets cumuls_regime
     * @return \Swagger\Client\Model\CumulRegime[]
     */
    public function getCumulsRegime()
    {
        return $this->cumuls_regime;
    }
  
    /**
     * Sets cumuls_regime
     * @param \Swagger\Client\Model\CumulRegime[] $cumuls_regime 
     * @return $this
     */
    public function setCumulsRegime($cumuls_regime)
    {
        
        $this->cumuls_regime = $cumuls_regime;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
